name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Node ${{ matrix.node-ver }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 12, 14]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-ver }}

      - name: Install Dev Dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test && npm run coverage
